name: env
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - --index-url https://download.pytorch.org/whl/cu121
    - --extra-index-url https://pypi.org/simple
    - torch==2.5.1
    - torchvision==0.20.1
    - numpy>=2
    - ultralytics
    - Pillow
    - huggingface_hub
    - einops
    - safetensors
    - open3d
    - opencv-python
    - transformers
    - setuptools<81
    - psutil
    - matplotlib
    - tqdm
    - pyrealsense2
    - iopath
    - timm
    - pycocotools
    - ftfy
    - projectaria-tools
    - scikit-learn
    - simple-lama-inpainting
    - rerun-sdk==0.26.2