name: pred_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - torch==2.6.0 --index-url https://download.pytorch.org/whl/cu124
    - torchvision
    - torchaudio
    - numpy
    - opencv-python
    - scikit-learn
    - open3d

